version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: hengly
      DB_PASSWORD: hengly168
      DB_NAME: blogdb
    networks:
      - shared_network

networks:
  shared_network:
    external: true
