FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY frontend/myapp/package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY frontend/myapp ./

# Expose React dev server port
EXPOSE 3000

# Start React app
CMD ["npm", "start"]
