version: "3.8"

services:
  backend:
    build:
      context: ..  # parent folder (includes backend/)
      dockerfile: docker/Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: hengly
      DB_PASSWORD: hengly168
      DB_NAME: blogdb
    networks:
      - shared_network
    depends_on:
      - db

  frontend:
    build:
      context: ..  # parent folder (includes frontend/)
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    networks:
      - shared_network
    depends_on:
      - backend

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: blogdb
      MYSQL_USER: hengly
      MYSQL_PASSWORD: hengly168
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - shared_network
 
networks:
  shared_network:
    driver: bridge

volumes:
  db_data:
