version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: blogdb
      MYSQL_USER: hengly 
      MYSQL_PASSWORD: hengly168
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - shared_network

networks:
  shared_network:
    external: true

volumes:
  db_data:
